# -*- coding: utf-8 -*-
"""orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_jbbrUdkdyhiNtFTkQ6gMWCRI6b6wL_

Example of addition
"""

a = 2
b = 3
c=a+b

print(c)

"""Example of string"""

greetings= "advise na, proff"
print(greetings)